ACTIVITY_PROMPT_VERSION = "activity-v1"
ACTIVITY_RETRIEVAL_TOP_K = 5
ACTIVITY_MAX_CONTEXT_CHARS = 10000

ACTIVITY_DEFAULT_MATERIALS = ["notebook", "pencil", "board"]
ACTIVITY_MAX_MATERIALS = 20
ACTIVITY_MATERIAL_MAX_CHARS = 100

ACTIVITY_TITLE_MAX_CHARS = 200
ACTIVITY_OBJECTIVE_MAX_CHARS = 1000
ACTIVITY_STEP_MAX_CHARS = 500
ACTIVITY_MAX_STEPS = 20
ACTIVITY_MAX_CITATIONS = 50
